### ISSUE TITLE
UIBarButtonItem position

### ISSUE THREAD

**Issue by Casporro** [Vaberer/Font-Awesome-Swift#1]
This library is awesome just like the font... but when I use it with a UIBarButtonItem the icon seems not to be aligned vertically with the title of the UINavigationBar and also very close from the boundary of the screen

**Comment by Vaberer** [comment]
Hello, thanks for your remark. I'll try to fix it in a next version:)

**Comment by YKSing** [comment]
Same problem here but I just solved this by changing the size to 18

**Comment by snaill** [comment]
see this: https://github.com/leberwurstsaft/FontAwesome-for-iOS

**Comment by Vaberer** [comment]
So finally, the best option how to fix a vertical alignment is set font size into 18pt. Since we do not want to align it every time (UILabel, UIButton) changing font makes a desired effect.

**Comment by hongzhou85** [comment]
18pt is too small. Any way to set option for center vertically?
