### ISSUE TITLE
Appending string text after icon

### ISSUE THREAD

**Issue by YKSing** [Vaberer/Font-Awesome-Swift#10]
I would like to have an option to append text after the icon (or prepend).
Will you consider working on this?
This is a useful library and I really thank you for making such good work for all developers.

**Comment by Vaberer** [comment]
Hello,

thanks for a good idea. I added this feature to version _1.3.0_ and you can use it like this:

`labelName.setFAText(prefixText: "follow me on ", icon: FAType.FATwitter, postfixText: ". Thanks!", size: 25)`

for more, look at the readme file:)

Best,

Patrik
