### ISSUE TITLE
[Feature] Different icon and text size

### ISSUE THREAD

**Issue by alvinnguyen** [Vaberer/Font-Awesome-Swift#13]
Very handy pod, just wondering whether it's possible to have the icon a bit larger than the text?

**Comment by Vaberer** [comment]
Hello,

Thanks for your suggestion.

Just update library to version 1.4.3 and you can use it like:

`buttonName.setFAText(prefixText: "follow me on ", icon: FAType.FATwitter, postfixText: ". Thanks!", size: 25, forState: .Normal, iconSize: 30)`

or

`labelName.setFAText(prefixText: "follow me on  ", icon: FAType.FATwitter, postfixText: ". Thanks!", size: 25, iconSize: 30)`

or check readme file :)

Best,

Patrik
