### ISSUE TITLE
Setting icons with variables as iconname

### ISSUE THREAD

**Issue by klaaskox** [Vaberer/Font-Awesome-Swift#14]
Awesome library!
I am loading data from a backend system which gives me an iconName-String.

for example:
let iconName = "FABicycle"

I know this might be more a generic Swift question, but is it possible to use this variable (iconName) to get the FAType.FABicycle? 

Thanks!

**Comment by Vaberer** [comment]
Hello

Thanks for very interesting way how you use the library :)

A came with this solution:

If you look at the `ViewController.swift` file, there is a variable called `helper` which contains all strings of the icons.

if you use it like this, it will work:

```
if let index = helper.indexOf("FATwitter") {

           labelName.FAIcon =  FAType(rawValue: index)
}
```

Best,

Patrik

**Comment by klaaskox** [comment]
Thanks a lot!

2015-11-30 8:34 GMT+01:00 Patrik Vaberer notifications@github.com:
