### ISSUE TITLE
UIButton Title Color not working in 1.4.3

### ISSUE THREAD

**Issue by alvinnguyen** [Vaberer/Font-Awesome-Swift#15]
Found out that 1.4.3 has the ability to set the UIButton font to another font rather than system font, which is awesome.

However, also found out that cannot set the title color of the button anymore in 1.4.3 (defaulting to black), reverting back to 1.4.2 fixes it.

Will check whether I can fix this.

**Comment by alvinnguyen** [comment]
Well, the issue I believe lay in those below code (and the like for icon)

```
let textAttribute = [NSFontAttributeName : titleLabel.font]
let myString = NSMutableAttributedString(string: prefixText, attributes: textAttribute )
```

as it does not carry the color to the string.

I've tried to do this 

```
titleLabel.textColor = titleLabel.textColor ?? UIColor.redColor()

let textAttribute = [NSFontAttributeName : titleLabel.font, NSForegroundColorAttributeName: titleLabel.textColor]
let myString = NSMutableAttributedString(string: prefixText, attributes: textAttribute )
```

which will work if you do this in your code

```
let buttonTextColor = UIColor.yellowColor()
// works
recipeButton.titleLabel?.textColor = buttonTextColor
// will not work
recipeButton.setTitleColor(buttonTextColor, forState: .Normal)
```

Will keep trying since I think declaring the color in the function should be the last resolution.

Any ideas?

**Comment by alvinnguyen** [comment]
Ignore this, silly me, just have to update readme to 

```
buttonName.titleLabel?.textColor = UIColor.redColor()
```

And it should work.

**Comment by Vaberer** [comment]
Hello

Thanks for testing the library and trying to find a solution..:)

I'll just update readme but I think the ultimate solution would be to change the color i.e:

```
setFATitle:forState
```
