### ISSUE TITLE
[Feature Request] UISlider support?

### ISSUE THREAD

**Issue by craigpearce5** [Vaberer/Font-Awesome-Swift#18]
I would love to use this on UISlider support such as `maximumValueImage` however it doesn't seem to work.  Any possibility of future support for UISlider?

**Comment by Vaberer** [comment]
Hello, thanks for the feature request, just update pods to 1.4.5 and it will work :) Fore more info, check readme.

```
// change minimum or maximum value image
  slider.setFAMinimumValueImage(.FABellSlashO)
  slider.setFAMaximumValueImage(.FABellO)

  // change minimum or maximum value image with a specific size
  slider.setFAMinimumValueImage(.FABellSlashO, customSize:  CGSizeMake(35, 35))
  slider.setFAMaximumValueImage(.FABellO, customSize:  CGSizeMake(35, 35))
```

**Comment by craigpearce5** [comment]
That's awesome!  Thanks very much.  Any plans to allow for `textColor:` as well?
