### ISSUE TITLE
Color on FAIcons

### ISSUE THREAD

**Issue by BasThomas** [Vaberer/Font-Awesome-Swift#2]
Hi Patrik,

was wondering if it's possible to use colors on the icons? Haven't worked that much with FA, but I'm not sure if it's at all possible... would be really nice, though.

**Comment by Vaberer** [comment]
Hello, thanks for asking. Since Font Awesome is just a text, you can change colors like this:

labelName.textColor = UIColor.redColor()
buttonName.tintColor = UIColor.redColor()
barButtonName.tintColor = UIColor.redColor()

I will also add this code into readme file for other people:)

**Comment by BasThomas** [comment]
Thx!

**Comment by Vaberer** [comment]
btw, I recommend to change color of buttons this way 

buttonName.setTitleColor(UIColor.redColor(), forState: .Normal)

It will solve this issue: https://github.com/Vaberer/Font-Awesome-Swift/issues/4

**Comment by BasThomas** [comment]
Used it only in labels, but thanks for the heads up :)

**Comment by Vaberer** [comment]
All right:)
