### ISSUE TITLE
Bottom part of text cut off

### ISSUE THREAD

**Issue by squeeish** [Vaberer/Font-Awesome-Swift#20]
I'm new to iOS programming. I've noticed that if I have a prefix containing the letters "g", "p", etc, the bottom part of the text is cut off when I use font awesome icons. 

![Imgur](http://i.imgur.com/LJlKAif.png)

Is there a workaround to that? That's [Swiftybutton](https://github.com/TakeScoop/SwiftyButton) by the way.

**Comment by wherewelive** [comment]
FYI, had the same issue and you can fix it using NSAttributedString and `setAttributedTitle` for buttons or labels.  Here is how to split the icon and text up into an NSAttributedString

`let iconPart = NSMutableAttributedString(string: "\(String.fontAwesomeIconWithName(.User))", attributes: [NSFontAttributeName:UIFont.fontAwesomeOfSize(12)])`

`let textPart = NSMutableAttributedString(string: " whatever your label is here", attributes: [NSFontAttributeName:UIFont.systemFontOfSize(12)])`

Then you need to append the textPart to the iconPart (notice the space left in the textPart string)

`iconPart.appendAttributedString(textPart)`

iconPart is now an NSAttributedString with 2 font types that will not cutoff the text :)

<img width="81" alt="screen shot 2016-02-17 at 2 12 25 pm" src="https://cloud.githubusercontent.com/assets/6101252/13126727/81135024-d580-11e5-970f-44aebd86df22.png">

**Comment by RanjitKadam** [comment]
hey I am also facing the same issue, but this lib, does not contain "fontAwesomeIconWithName"

**Comment by wherewelive** [comment]
I was using a different lib (https://github.com/thii/FontAwesome.swift) but idea would be the same here since the icon is just a string

**Comment by Vaberer** [comment]
Thank you guys for a hint how to fix it. New version of Font Awesome works great!

**Comment by cschar** [comment]
If anyones wondering how to get that Attributed String into a BarButton Item (which doesnt accept multi attributed strings....) You can override the customView with a label and set it from there:

   ```swift
        let iconPart = NSMutableAttributedString(string: "\(String.fontAwesomeIcon( name: .videoCamera))", attributes: [NSAttributedStringKey.font:UIFont.fontAwesome(ofSize: 24)])

        let textPart = NSMutableAttributedString(string: "Video", attributes: [NSAttributedStringKey.font: UIFont.systemFont(ofSize: 16)])

        iconPart.append(textPart)
        let label = UILabel()
        label.attributedText = iconPart
        label.sizeToFit()
        label.textColor = self.view.tintColor


        let tap = UITapGestureRecognizer(target: self, action: #selector(MyViewController.tapFunction))
        label.isUserInteractionEnabled = true
        label.addGestureRecognizer(tap)
        MyBarButton.customView = label


//elsewhere in your view Controller:
    @objc
    func tapFunction(sender:UITapGestureRecognizer) {
        print("tap working")
    }
```
