### ISSUE TITLE
Not able to set the button color using setFATitleColor?

### ISSUE THREAD

**Issue by ansu** [Vaberer/Font-Awesome-Swift#24]
let icon = resultSearchController.active ? FAType(rawValue: helper.indexOf(filteredData[indexPath.row])!) : FAType(rawValue: indexPath.row)
        c.lSmall.FAIcon = icon
        c.lMedium.FAIcon = icon
        c.lBig.FAIcon = icon
        c.lBig.textColor = UIColor.redColor()
        c.iIcon.setFAIconWithName(icon!, textColor: UIColor.blackColor())
        c.lButton.setFAIcon(icon!, forState: .Normal)
        c.lButton.setFATitleColor(UIColor.redColor())

Button color is not coming in red but lBig lable color is in red.

**Comment by Vaberer** [comment]
thanks for reporting a bug. update to 1.4.7 and it will work:)

Patrik
