### ISSUE TITLE
Can't find bundle / No such file or directory [cocoapods beta7 issue]

### ISSUE THREAD

**Issue by salverde** [Vaberer/Font-Awesome-Swift#25]
`error: /path/to/home/Library/Developer/Xcode/DerivedData/App-xxx/Build/Products/Debug-iphonesimulator/Font-Awesome-Swift/Font-Awesome-Swift.bundle: No such file or directory`

CocoaPods version: 1.0.0.beta.6
pod 'Font-Awesome-Swift', '~> 1.4.6'
platform :ios, '8.0'

any thoughts?

**Comment by yachi** [comment]
cocoapods' issue

https://github.com/CocoaPods/CocoaPods/issues/5034

**Comment by Vaberer** [comment]
thanks @yachi. Either wait for beta7 or reinstall cocoapods to a lower version
