### ISSUE TITLE
text font missing when using "setFAText" for multiple times 

### ISSUE THREAD

**Issue by lukedesu** [Vaberer/Font-Awesome-Swift#26]
I have experienced that If I call setFAText for multiple times, the button font which has been defined in storyboard or code will missing. Is that a bug or something I did wrong? One thing I have figured out is that it looks somewhat related to button type (mine is custom).

My code as below:  

```
override func viewDidAppear(animated: Bool) {
  super.viewDidAppear(true)
  setText()
}

func setText(){
  locationLabel.setFAText(prefixText: "", icon: FAType.FALocationArrow, postfixText: " "+"Current Location".localized(), size: 15, forState: .Normal)
}
```

Thanks~

**Comment by Vaberer** [comment]
thanks for reporting a bug. update to 1.4.7 and it will work:)

Patrik

**Comment by othyn** [comment]
Ignore that, mistyped.
