### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by Leinadzet** [Vaberer/Font-Awesome-Swift#31]
Hi,

will there be Swift3.0 support? 

Seems like this line does not suit:

let myString = NSMutableAttributedString(string: prefixText, attributes: textAttribute )

Error: "Cannot convert value of type [String: UIFont?] to expected argument type [String:AnyObject?]

**Comment by SNagra** [comment]
I just added a pull request with Swift 3.0 support.
