### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by mhermosi** [Vaberer/Font-Awesome-Swift#34]
in class FontLoader line 324:

fontURL = bundle.URLForResource(FAStruct.FontName, withExtension: "ttf", subdirectory: "Font-Awesome-Swift.bundle")!

just updated (pod install) and pod installed version 1.4.6

updated to version 1.4.8 and still have the issue. for some weird reason still pointing to line 324 but
there are no code there.. I cleaned up and build the project.. simple don't understand.

**Comment by levin-ilya** [comment]
+1 getting same issue.

**Comment by SNagra** [comment]
Just put in a new pull request that may fix this. Check out the fork I have on the Swift 3.0 branch and let me know if it fixes this issue.

https://github.com/SNagra/Font-Awesome-Swift

**Comment by Vaberer** [comment]
thanks @SNagra

**Comment by Vaberer** [comment]
Fixed. Thanks
