### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by paixsn** [Vaberer/Font-Awesome-Swift#36]
is a support carthage planned?

**Comment by artshin** [comment]
I forked the latest repo and added Carthage support right [here](https://github.com/Arcanfel/Font-Awesome-Swift)

**Comment by ivdma** [comment]
@Arcanfel awesome, could you submit a pull request to this repo? 
Maybe @Vaberer will accept and merge it.

**Comment by artshin** [comment]
@ivdma I'll give it a shot

**Comment by Vaberer** [comment]
Thanks for the contribution! Will update version on readme and it's working
