### ISSUE TITLE
Attempting to set imageView of a UITableViewCell

### ISSUE THREAD

**Issue by stevenlevin** [Vaberer/Font-Awesome-Swift#37]
Not sure if this is a bug or I am missing something in my code.   When I set the imageView object of a UITableViewCell nothing happens.

`cell.imageView?.setFAIconWithName(FAType.FAGithub, textColor: UIColor.blackColor())`

Thanks for your assistance

**Comment by stevenlevin** [comment]
I overcame this issue by setting the frame size before setting the icon

`cell.imageView?.frame.size = CGSize(width: 30, height: 30)`

**Comment by bohachevskyy** [comment]
@stevenlevin 

Works for me! Thanks!
