### ISSUE TITLE
Problem when tap a button a change state to selected

### ISSUE THREAD

**Issue by Casporro** [Vaberer/Font-Awesome-Swift#4]
I have a UIButton with FAHeartO for state .Normal and FAHeart for state selected but when I change the state to selected at user taps the button the colors change.
If I have a normal button whit tintColor set to redColor in normal state but the selected estate shows the FAHeart in whiteColor and the background in redColor. I need the FAHeart in redColor with clearColor in the background.
Is this a bug?

**Comment by Casporro** [comment]
I saw the same problem here: http://stackoverflow.com/questions/31052227/avoid-uibutton-inverted-colours-when-selected?s=1|4.1570

**Comment by Vaberer** [comment]
Hello, i looked at this problem and you are right - this is a global issue of UIButtons. However you can easily solve this problem -  just change button type to Custom (i.e. in Storyboard in the _Attribute inspector_)

and you can change color for Selected state by 
`buttonName.setTitleColor(UIColor.redColor(), forState: .Selected)`

and you will reach a desired effect.
Let me know if it worked to you.

Have a nice day.

Patrik

**Comment by Casporro** [comment]
Hello Patrik,
You're right, thank you!

Have a nice day you too.
