### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by bgatelet** [Vaberer/Font-Awesome-Swift#43]
FontAwesome is causing a fatal error after updating to swift 3. The error is found in FAIcon.swift, line 130, font = fontAwesome! is nil. Code is cell.displayLabel.FAIcon = FAType.FAStar .

Pod is up to date at 1.4.8 on branch swift-3.

**Comment by Vaberer** [comment]
New version should fix the problem. Thanks to @george-gw
