### ISSUE TITLE
Swift 3 - Can you please deploy 1.4.9 on cocoapods ?

### ISSUE THREAD

**Issue by iNono22** [Vaberer/Font-Awesome-Swift#46]
https://github.com/Vaberer/Font-Awesome-Swift/tree/swift-3

**Comment by iNono22** [comment]
Thanks for the tag, but can you deploy for Cocoapods?
Ping @Vaberer

**Comment by iNono22** [comment]
Any update?

**Comment by choiks14** [comment]
None of your spec sources contain a spec satisfying the dependency: `Font-Awesome-Swift (~> 1.4.9)`.

what is this?

**Comment by Vaberer** [comment]
Hello guys, thanks for the patience. After tons of errors, I finally could deploy new version 1.5.0. Let me know if all works for you, too.

**Comment by wagnercasey** [comment]
I'm getting a successful pod install but when I try to use an icon I get:

`assertion failed: ****** FONT AWESOME SWIFT - FontAwesome font not found in the bundle or not associated with Info.plist when manual installation was performed. ******: file /Users/wagnc/Documents/Main Dev/fontcheck2/Pods/Font-Awesome-Swift/Source/FAIcon.swift, line 61
2016-10-06 11:27:24.567453 fontcheck2[12149:2216037] assertion failed: ****** FONT AWESOME SWIFT - FontAwesome font not found in the bundle or not associated with Info.plist when manual installation was performed. ******: file /Users/wagnc/Documents/Main Dev/fontcheck2/Pods/Font-Awesome-Swift/Source/FAIcon.swift, line 61`

**Comment by Vaberer** [comment]
1.5.1 works. thanks
