### ISSUE TITLE
Stacked Icons Support

### ISSUE THREAD

**Issue by ripegooseberry** [Vaberer/Font-Awesome-Swift#53]
Font awesome supports stacking icons as layers into one icon. http://fontawesome.io/examples/#stacked
Do you plan to introduce support for this? 

----- example code i use right now to combine two icons:
Right now, for example to have a black Plus Icon within a yellow circle (musical.ly style) I would do:

        let imageTopSize = CGSizeMake(44,44)
        let imageBGSize = CGSizeMake(80,80)

        let imageTopRect = CGRectMake((imageBGSize.width - imageTopSize.width)/2, (imageBGSize.height - imageTopSize.height)/2, imageTopSize.width, imageTopSize.height)
        let imageBGRect = CGRectMake(0,0,imageBGSize.width, imageBGSize.height)
        
        let imageTop = UIImage(icon: .FAPlus , size: imageBGSize,  textColor: UIColor.blackColor())
        let imageBG = UIImage(icon: .FACircle , size: imageTopSize,  textColor:UIColor.yellowColor())

        UIGraphicsBeginImageContextWithOptions(imageBGRect.size, false, 0.0)
        imageBG.drawInRect(imageBGRect)
        imageTop.drawInRect(imageTopRect)
        let imageCombined = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        let tabBarItemCreateImage = imageCombined!.imageWithRenderingMode(UIImageRenderingMode.AlwaysOriginal)

**Comment by jaimeagudo** [comment]
Good suggestion @ripegooseberry . I'd find useful too to stack the icon over an UIImage so we could construct kind of _badges_ over photos. Another common usage for me is to have different font styles for the prefix & postfix text, currently using https://github.com/Raizlabs/BonMot

If I come up with a nice integration I'll submit a PR

Thanks everyone

**Comment by Vaberer** [comment]
Thanks for the contribution!
