### ISSUE TITLE
icon shows up half the time

### ISSUE THREAD

**Issue by uknowmeright** [Vaberer/Font-Awesome-Swift#56]
I am using this framework and trying to load in Icons in table view cells. SUPER buggy
The closest I have come to getting it to work properly is to create an image and use .setFAIconWithName:

`usernameIconImage.setFAIconWithName(.FAMobile, textColor: UIColor.blackColor())`

This only shows up half the time. I have considered putting it in a dispatch get main function but that causes the tableview to become choppy. 

I also just get a questionmark icon if I try it with a label and try to put text in there with it:

`self.usernameLabel.setFAText(prefixText: "", icon: .FAMobile, postfixText: " " + theDisplayedName, size: 18, iconSize: 19)`

Anyone else experiencing this?

Looks like I will have to use another framework =(

**Comment by Vaberer** [comment]
Hello, are you using it in a background thread? Updating UI has to be done only in main thread.
