### ISSUE TITLE
FontAwesome for Swift 2.3?

### ISSUE THREAD

**Issue by waseefakhtar** [Vaberer/Font-Awesome-Swift#61]
I use the Swift 2.3 branch and added Pod as:

`pod 'Font-Awesome-Swift', '~> 1.4.8’`

But that give me syntax errors in FASwift. Where am I gone wrong?

**Comment by Vaberer** [comment]
Hello, try to specify branch like
pod 'Font-Awesome-Swift', :branch => 'swift-2.3'
for more info: https://guides.cocoapods.org/using/the-podfile.html
