### ISSUE TITLE
Set text at bottom of UIButton

### ISSUE THREAD

**Issue by juanbrusco** [Vaberer/Font-Awesome-Swift#72]
How can I set the text at the bottom of button? Only support prefix and postfix? 
Thanks!

**Comment by pumplerod** [comment]
Would love to be able to do this as well.  I've tried adding a "\n" to the postfix but that seems to only make the text disappear. 

I am able to accomplish the effect by adding a UILabel SubView to my button, but then you need to do some extra work if you also want the UILabel to act as the button when clicked.
