### ISSUE TITLE
Error ambiguous reference to member

### ISSUE THREAD

**Issue by wallace7souza** [Vaberer/Font-Awesome-Swift#82]
Hi guys!
I'm facing this error on xcode. i have no idea what to do.
Thks to lib btw.

![erro-fontawesome](https://user-images.githubusercontent.com/3328434/26860241-553c03ec-4b13-11e7-8684-69089f38ed18.png)

**Comment by Vaberer** [comment]
Hello, please update Font Awesome Swift to 1.6.4. Happy coding! ;)
