### ISSUE TITLE
Setting isEnabled = false on UIBarButtonItem

### ISSUE THREAD

**Issue by bingjiang** [Vaberer/Font-Awesome-Swift#92]
Results in ? icon below. Running on iOS 11

![img_e93cbfa6a251-1](https://user-images.githubusercontent.com/8406869/31502828-b43d6f06-afa0-11e7-8906-d5585ad9f5aa.jpeg)

**Comment by Vaberer** [comment]
The issue is fixed. Please update to 1.7.1. Thanks
