### ISSUE TITLE
iOS11 UIBarButtonItem icon disappear on press

### ISSUE THREAD

**Issue by bingjiang** [Vaberer/Font-Awesome-Swift#95]
In iOS 11 when pressing the the UIBarButtonItem, it causes the icon to disappear

**Comment by peterforeman** [comment]
Ah! I thought it was me. Same here, pressing it shows a square with a ? in it.

**Comment by makzink** [comment]
same here. Any solution?

**Comment by felixk** [comment]
There is a pull request that fixes it. #93

**Comment by Vaberer** [comment]
Hello, please update to 1.7.2 Thanks for your contribution and using Font Awesome Swift.
